services:
  db:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    command: postgres -c 'max_connections=10000'
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  
  amigoscode-api:
    container_name: amigoscode-api
    image: ahowell2000/amigoscode-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    ports:
      - "8085:8085"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  amigoscode-react:
    container_name: amigoscode-react
    image: ahowell2000/amigoscode-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:80
    ports:
      - "3000:5173"
    depends_on:
      - amigoscode-api
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db:
  
